import random


def quote_generator():
    return random.choice(
                    [
                        "File names are blinded, slay!",
                        "That was so easy dawg.",
                        "Guys, we are making real data!",
                        "It be like that sometimes.",
                        "¡Ay caramba! Could this program be any faster?",
                        "I’m Screaming!!! Nice job processing the files!",
                        "Keep slaying the day",
                        "Blinded files? Facts.",
                        "Like and Subscribe",
                        "Microtubules are the best cytoskeleton filament",
                        "Now your images are C. Elegant",
                        "Speedier than S. cerevisiae ferments!",
                        "Faster than a fly.",
                        "Ate and left no crumbs",
                        "https://www.youtube.com/watch?v=Aq5WXmQQooo&list=RDAq5WXmQQooo&start_radio=1",
                        "Never gonna give you up, never gonna let you down, never gonna run around and desert you",
                        "Oy with the poodles already",
                        "Hey kids, spelling is fun! - Taylor Swift",
                        "I cry a lot, but I am so productive – Taylor Swift",
                        "Gotta catch them all!",
                        "God, what have you done? You’re a pink pony girl.",
                        "Just cause you put syrup on somethin’ don’t make it pancakes ",
                        "Some seriously bad juju mcgumbo went down here",
                        "Y’all hear about pluto? That’s messed up",
                        "What’s new Scooby Doo?",
                        "Zoinks Scoob!",
                        "They don’t think it be like that, but it do. - Oscar Gamble",
                        "I’m not superstitious, but I am a little stitious. - Michael Scott",
                        "Leslie, I typed your symptoms into the thing up here, and it says you could have network connectivity problems.",
                        "Treat! Yo! Self! To some file name blinding",
                        "I made my money the old fashioned way: I got run over by a Lexus. – Jean Ralphio Sapperstein",
                        "I can do what I want. – Ron Swanson",
                        "Uh Oh Spaghettio",
                        "it's tough to be a bug",
                        "may the force be with you",
                        "just keep swimming",
                        "to infinity and beyond!",
                        "i solemnly swear that i am up to no good",
                        "accio blinded files!",
                        "Yoo hoo Big summer blowout!",
                        "Yabba dabba doo!",
                        "Surely you can't be serious? I am serious... and don't call me Shirley.",
                        "You got it dude!",
                        "Hakuna Matata!",
                        "Blinded by the light",
                        "Me? a princess? Shut up",
                        "My name is Inigo Montoya. You killed my father. Prepare to die.",
                        "untap, upkeep, girlboss",
                        "I am Groot.",
                        "Blinded your files, I have",
                        "Live long and prosper.",
                        "You're killing me smalls!",
                        "Why so serious?",
                        "You sit on a throne of lies. - Buddy the Elf",
                        "Smarter than the average bear.",
                        "I refuse to answer on the grounds that I do not know the answer. - Douglas Adams",
                        "As a boy, I wanted to be a train. Now I am one with blinding files.",
                        "I go to seek a great perhaps.",
                        "How you doin'?",
                        "D'oh!",
                        "No soup for you!",
                        "Yada yada yada.",
                        "To the batmobile!",
                        "Bazinga!",
                        "You shall not pass!",
                        "Vote for Pedro.",
                        "Life is like a box of chocolates.",
                        "I feel the need—the need for speed!",
                        "You are without a doubt the worst pirate I have ever heard of. - Captain Barbosa",
                        "Four for you, Glen Coco! You go, Glen Coco!",
                        "It's Morbin time!",
                        "Put that thing back where it came from or so help me. - Monsters Inc.",
                        "Kachow!",
                        "IT'LL QUENCH YA, IT'S THE QUENCHIEST! - Sokka, Avatar the Last Airbender",
                        "Life happens wherever you are, whether you make it or not. - Uncle Iroh",
                        "Blinding out the haters since 2026.",
                        "Blinded files: Brought to you by a confused grad student",
                        "As a child, I yearned for the mines - Jack Black, Minecraft movie",
                        "I am McLovin' it!",
                        "Get Shreked!",
                        "The risk I took was calculated, but man, am I bad at math. - Percy Jackson",
                        "With great power, comes great need to take a nap. - Nico di Angelo",
                        "Blinded files? Challenge accepted. - Barney Stinson",
                        "I scream, you scream, we all scream for blinded files!",
                        "Just keep blinding, just keep blinding. - Dory",
                        "She doesn't even go here! - Damian, Mean Girls",
                        "No one believed it would work. Especially me.",
                        "We did it Joe!",
                        "Something happened. It worked?",
                        "Got Milk?",
                        "Please don't dull my sparkle",
                        "Runs on audacity and caffeine",
                        "Live Mas",
                        "Ew, David - Alexis Rose",
                        "When life gives you lemonade, make lemons. Life will be all like 'What?!' - Phil Dunphy",
                        "Why is nobody having a good time? I specifically requested it. - Cpt Holt",
                        "Troy and Abed in the morning!",
                        "Wubba Lubba Dub Dub! - Rick Sanchez",
                        "I am the one who knocks! - Walter White",
                        "When there's trouble, you know who to call! - Teen Titans",
                        "Who you gonna call? GHOSTBUSTERS",
                        "You'll never get answers if you're afraid to ask the questions.",
                        "I'm just a gorl",
                        "Ah yes. Science.",
                        "Science? in the year of our lord 2026?",
                        "POV: you're a blinded file",
                        "what does this even mean?",
                        "If this breaks, it's a future me problem",
                        "I have no idea what I'm doing, but I'm doing it.",
                    ]
                )